import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lang: string
  }
}

export default function RootLayout({
  children,
  params: {lang},
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={lang}>{children}</html>
  );
}
