import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string
  }
}

export default function RootLayout({
  children,
  params: {locale},
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      {children}
    </html>
  );
}
